Traceback (most recent call last):
  File "src/the_logic/market_maker_trader.py", line 70, in <module>
    main()
  File "src/the_logic/market_maker_trader.py", line 28, in main
    logic(iter_)
  File "src/the_logic/market_maker_trader.py", line 37, in logic
    model_object_dict = mm_scoring.get_model_objects()
  File "/mnt/src/lib/market_maker_scoring.py", line 242, in get_model_objects
    model_object_dict[model_path] = self.get_pickle_from_s3(model_path)
  File "/mnt/src/lib/market_maker_scoring.py", line 255, in get_pickle_from_s3
    obj = self.s3_client.get_object(Bucket=self.s3_bucket, Key=s3_key)
  File "/usr/local/anaconda/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/anaconda/lib/python3.6/site-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/anaconda/lib/python3.6/site-packages/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/anaconda/lib/python3.6/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Key, value: ['model_objects/market_maker_model_ethusdt_10.pkl', 'market_maker_model_ethusdt_10.pkl'], type: <class 'list'>, valid types: <class 'str'>
Failed with exit code: 1
